// The L2L levels document, shared by the marking tool, the live dashboard and the tests that hold both.
//
// One implementation, three readers, because the artifact has to mean the same thing wherever it is
// written. `data/l2l-levels.json` is the only store: a level is either a `seed` (a price the user marked
// by hand on the chart) or `derived` (a copy a duplication generated from the distance between two
// seeds). Everything here is that document - how an edit is validated, how the ladder is measured from
// the seeds, how the file is serialised, and how the published file is written back to the reader's own
// GitHub account. It places nothing, reads no account and holds no credential of its own: the token the
// published page needs is supplied by the reader at publish time and lives in their browser, never here.
//
// Loaded as a plain script by index.html (the global `L2LLevelsStore`) and required by
// scripts/l2l-levels-tool.js and by node tests, so the writer, the page and the checker cannot drift.
(function initL2lLevelsStore(root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }

  const globalRoot = root || (typeof globalThis !== "undefined" ? globalThis : this);
  globalRoot.L2LLevelsStore = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function createL2lLevelsStore() {
  const SCHEMA_VERSION = "l2l-levels-v1";
  const DEFAULT_STATE_PATH = "data/l2l-levels.json";
  const DEFAULT_PORT = 8788;
  const ALLOWED_KINDS = ["l2l", "half-l2l", "level"];
  const ALLOWED_DIRECTIONS = ["long", "short", "both"];
  // A level is either a `seed` - one of the prices the user marked by hand on the chart - or `derived`
  // - one of the copies a duplication generated from the distance between two seeds. The distinction is
  // what makes the ladder reproducible: the seeds are the measurement, the derived levels are its
  // consequences, and only the seeds are ever held to be hand-marked judgement.
  const ALLOWED_ROLES = ["seed", "derived"];
  const DERIVED_MARKED_BY = "dashboard duplicate";
  const ALLOWED_ACTIONS = ["add", "remove", "clear", "duplicate"];
  // A duplication repeats the seed distance this many steps each way unless the request says otherwise.
  // Ten each way is the ladder the dashboard offers by default and the cap leaves room for extensions;
  // lib/l2l_ladder.js carries the same two numbers for the page's own reading, and the tests pin them
  // together. Zero is a legal count (the ladder runs one way only).
  const DEFAULT_DUPLICATE_STEPS = 10;
  const MAX_DUPLICATE_STEPS = 60;
  const DEFAULT_TIMEFRAME = "M5";
  // The four instruments the live feed publishes, in dashboard order. The file starts with all four and
  // empty level lists so nothing downstream has to guess whether a symbol was never marked or was dropped.
  const KNOWN_INSTRUMENTS = [
    { symbol: "EURUSD", dashboard_asset: "EUR" },
    { symbol: "XAUUSD", dashboard_asset: "GOLD" },
    { symbol: "US100.cash", dashboard_asset: "NQ" },
    { symbol: "BTCUSD", dashboard_asset: "BTC" }
  ];

  const PRICE_TOLERANCE = 1e-9;
  // The provenance of a level a person marked on the dashboard's chart, as opposed to one the dashboard
  // generated by duplicating. It names where the price came from, not which writer saved the file.
  const LEVEL_MARKED_BY = "dashboard marking tool";

  // Who last wrote the file. The two writers share one schema and one note; only the name of the writer
  // differs, so a reader can always tell an edit made on the dashboard from one made by the local tool.
  const MARKED_BY = {
    tool: "local marking tool (scripts/l2l-levels-tool.js)",
    dashboard: "live dashboard marking (script.js + lib/l2l_levels_store.js)"
  };
  // The file's own note travels with it, so it says what a reader of the raw JSON needs to know without
  // opening the dashboard: who can write it, that the published page only reads it, and that an empty
  // instrument means nothing was marked rather than something went missing.
  const NOTE = "L2L level prices marked by the user on the dashboard chart. Levels with role seed are hand-marked anchors; levels with role derived are copies a duplication generated from the distance between two seeds. The live dashboard writes this file back to the repository with the reader's own GitHub token, and the loopback marking tool writes it on the reader's own machine; a browser keeps a local draft until a write is committed. Empty instruments mean nothing has been marked for that symbol yet, which is not an error.";

  function isFiniteNumber(value) {
    return typeof value === "number" && Number.isFinite(value);
  }

  function isTimestamp(value) {
    return typeof value === "string" && value.length > 0 && !Number.isNaN(Date.parse(value));
  }

  function roundPrice(value) {
    return Number(Number(value).toFixed(6));
  }

  function createEmptyState(nowIso, markedBy) {
    return {
      schema_version: SCHEMA_VERSION,
      generated_at_utc: nowIso,
      marked_by: markedBy || MARKED_BY.tool,
      note: NOTE,
      instrument_count: KNOWN_INSTRUMENTS.length,
      instruments: KNOWN_INSTRUMENTS.map(entry => ({
        symbol: entry.symbol,
        dashboard_asset: entry.dashboard_asset,
        levels: []
      }))
    };
  }

  function stateInstrumentMap(state) {
    const map = {};
    (Array.isArray(state?.instruments) ? state.instruments : []).forEach(entry => {
      if (entry && typeof entry.symbol === "string") map[entry.symbol] = entry;
    });
    return map;
  }

  // How many levels a duplication generates on one side of the seed pair, as a request supplies it.
  function normaliseStepCount(value, name) {
    if (value === undefined || value === null || value === "") return { value: DEFAULT_DUPLICATE_STEPS };
    const count = Number(value);
    if (!Number.isInteger(count) || count < 0 || count > MAX_DUPLICATE_STEPS) {
      return { error: `${name} must be an integer between 0 and ${MAX_DUPLICATE_STEPS}` };
    }
    return { value: count };
  }

  // A marking click arrives as a small JSON body. Everything is checked here rather than in the browser,
  // because this is the file that ends up committed - whichever of the two writers sent it.
  function normaliseEdit(body, nowIso) {
    if (!body || typeof body !== "object" || Array.isArray(body)) {
      return { error: "Request body must be a JSON object" };
    }
    const action = body.action === undefined ? "add" : body.action;
    if (!ALLOWED_ACTIONS.includes(action)) {
      return { error: `action must be one of ${ALLOWED_ACTIONS.join(", ")}` };
    }
    const symbol = typeof body.symbol === "string" ? body.symbol.trim() : "";
    if (!symbol) return { error: "symbol is required" };
    if (!Object.prototype.hasOwnProperty.call(stateInstrumentMap(createEmptyState(nowIso)), symbol)) {
      return { error: `unknown symbol: ${symbol}` };
    }

    // Clearing and duplicating act on the levels a symbol already carries, so they send no price: the
    // duplicating distance is measured from the file's own seed levels rather than from the request.
    if (action === "clear") {
      return { edit: { action, symbol, at: nowIso } };
    }
    if (action === "duplicate") {
      const timeframe = body.timeframe === undefined || body.timeframe === "" ? DEFAULT_TIMEFRAME : String(body.timeframe);
      const above = normaliseStepCount(body.above, "above");
      if (above.error) return { error: above.error };
      const below = normaliseStepCount(body.below, "below");
      if (below.error) return { error: below.error };
      const point = body.point === undefined || body.point === null ? null : Number(body.point);
      if (point !== null && (!isFiniteNumber(point) || point <= 0)) {
        return { error: "point must be a positive number when given" };
      }
      return {
        edit: {
          action,
          symbol,
          at: nowIso,
          above: above.value,
          below: below.value,
          point,
          // The generated levels share one template: only their price, step and spacing differ.
          level: {
            kind: "l2l",
            direction: "both",
            timeframe,
            marked_at_utc: nowIso,
            marked_by: DERIVED_MARKED_BY,
            note: ""
          }
        }
      };
    }

    const price = roundPrice(Number(body.price));
    if (!isFiniteNumber(price) || price <= 0) return { error: "price must be a positive number" };

    if (action === "remove") {
      return { edit: { action, symbol, price, at: nowIso } };
    }

    const kind = body.kind === undefined || body.kind === "" ? "l2l" : String(body.kind);
    if (!ALLOWED_KINDS.includes(kind)) {
      return { error: `kind must be one of ${ALLOWED_KINDS.join(", ")}` };
    }
    const direction = body.direction === undefined || body.direction === "" ? "both" : String(body.direction);
    if (!ALLOWED_DIRECTIONS.includes(direction)) {
      return { error: `direction must be one of ${ALLOWED_DIRECTIONS.join(", ")}` };
    }
    const role = body.role === undefined || body.role === "" ? "seed" : String(body.role);
    if (!ALLOWED_ROLES.includes(role)) {
      return { error: `role must be one of ${ALLOWED_ROLES.join(", ")}` };
    }
    const timeframe = body.timeframe === undefined || body.timeframe === "" ? DEFAULT_TIMEFRAME : String(body.timeframe);
    const label = body.label === undefined || body.label === "" ? `${kind} ${price}` : String(body.label);
    const note = body.note === undefined ? "" : String(body.note);

    return {
      edit: {
        action,
        symbol,
        price,
        at: nowIso,
        level: {
          label,
          price,
          kind,
          direction,
          role,
          timeframe,
          marked_at_utc: nowIso,
          marked_by: LEVEL_MARKED_BY,
          note
        }
      }
    };
  }

  // The two hand-marked levels are the seed pair: the highest and the lowest of a symbol's seed levels,
  // and the distance between them is the step. Duplicating repeats that exact distance above the top and
  // below the bottom, so the whole grid comes from one measurement the user made on the chart rather than
  // from a number typed in. Levels a previous duplication generated are replaced rather than stacked, so
  // re-running after a seed is moved cannot leave stale copies behind. Seed levels are never removed here.
  function buildLadder(levels, edit) {
    const seeds = levels.filter(level => level.role !== "derived");
    if (seeds.length < 2) {
      return { error: `duplicating needs the two seed levels marked first; ${edit.symbol} has ${seeds.length}` };
    }
    const prices = seeds.map(level => Number(level.price));
    const top = Math.max(...prices);
    const bottom = Math.min(...prices);
    const distance = roundPrice(top - bottom);
    if (!(distance > 0)) {
      return { error: `the seed levels for ${edit.symbol} are ${distance} apart, so there is no distance to repeat` };
    }

    const point = isFiniteNumber(edit.point) && edit.point > 0 ? edit.point : null;
    const taken = new Set(prices);
    const generated = [];
    // A derived price is snapped onto the instrument's point grid when the request carries one, so every
    // generated line is a price that could be typed into MT5 rather than a floating-point remainder.
    const addStep = (raw, step) => {
      const snapped = point ? Number((Math.round(raw / point) * point).toFixed(6)) : roundPrice(raw);
      if (taken.has(snapped)) return;
      taken.add(snapped);
      generated.push({
        ...edit.level,
        label: `derived ${snapped}`,
        price: snapped,
        role: "derived",
        spacing_price: distance,
        spacing_points: point ? Math.round(distance / point) : null,
        anchor_high: top,
        anchor_low: bottom,
        note: `Step ${step > 0 ? `+${step}` : step} of the L2L distance ${distance} measured between the seed levels ${bottom} and ${top}.`
      });
    };
    for (let step = 1; step <= edit.above; step += 1) addStep(top + step * distance, step);
    for (let step = 1; step <= edit.below; step += 1) addStep(bottom - step * distance, -step);
    if (!generated.length) {
      return { error: `duplicating generated no new levels for ${edit.symbol}` };
    }

    return {
      levels: seeds.concat(generated),
      generated: {
        count: generated.length,
        spacing_price: distance,
        spacing_points: point ? Math.round(distance / point) : null,
        anchor_high: top,
        anchor_low: bottom,
        above: edit.above,
        below: edit.below
      }
    };
  }

  // Adding the same price twice replaces that level instead of stacking duplicates, so a mis-click costs
  // one more click rather than a second line on the chart at the same price. Every entry is rebuilt from
  // KNOWN_INSTRUMENTS, so the file always carries all four symbols in dashboard order. `markedBy` names
  // the writer that last touched the file; it defaults to the loopback tool, which is the writer that
  // existed first, and the live dashboard passes its own name.
  function applyLevelEdit(state, edit, nowIso, markedBy) {
    const base = state && typeof state === "object" ? state : createEmptyState(nowIso, markedBy);
    const previous = stateInstrumentMap(base);
    const instruments = KNOWN_INSTRUMENTS.map(entry => {
      const existing = previous[entry.symbol];
      return {
        symbol: entry.symbol,
        dashboard_asset: entry.dashboard_asset,
        levels: Array.isArray(existing?.levels)
          ? existing.levels.filter(level => isFiniteNumber(level?.price) && Number(level.price) > 0)
          : []
      };
    });
    const target = instruments.find(entry => entry.symbol === edit.symbol);

    const result = (generated) => ({
      state: {
        schema_version: SCHEMA_VERSION,
        generated_at_utc: nowIso,
        marked_by: markedBy || MARKED_BY.tool,
        note: base.note || createEmptyState(nowIso, markedBy).note,
        instrument_count: instruments.length,
        instruments
      },
      generated: generated || null
    });

    if (edit.action === "clear") {
      if (!target.levels.length) return { error: `no levels marked for ${edit.symbol}` };
      target.levels = [];
      return result({ cleared: true, symbol: edit.symbol });
    }
    let summary = null;
    if (edit.action === "duplicate") {
      const duplicated = buildLadder(target.levels, edit);
      if (duplicated.error) return { error: duplicated.error };
      target.levels = duplicated.levels;
      summary = duplicated.generated;
    } else {
      const matchIndex = target.levels.findIndex(level => Math.abs(Number(level.price) - edit.price) <= PRICE_TOLERANCE);
      if (edit.action === "remove") {
        if (matchIndex === -1) return { error: `no level marked at ${edit.price} for ${edit.symbol}` };
        target.levels.splice(matchIndex, 1);
      } else if (matchIndex === -1) {
        target.levels.push({ ...edit.level });
      } else {
        target.levels[matchIndex] = { ...edit.level };
      }
    }
    target.levels.sort((a, b) => Number(b.price) - Number(a.price));

    return result(summary);
  }

  function serialiseState(state) {
    return `${JSON.stringify(state, null, 2)}\n`;
  }

  // Every writer trusts this file, so the same rules are checked on the way out - by the local tool
  // before it writes, and by the dashboard before it commits. Nothing here is a trading rule: it is
  // shape, provenance and duplicate protection.
  function validateLevelsState(state) {
    const errors = [];
    if (!state || typeof state !== "object" || Array.isArray(state)) {
      return ["Levels artifact must be a JSON object"];
    }
    if (state.schema_version !== SCHEMA_VERSION) errors.push(`schema_version must be ${SCHEMA_VERSION}`);
    if (!isTimestamp(state.generated_at_utc)) errors.push("generated_at_utc must be a parseable timestamp");
    if (typeof state.marked_by !== "string" || !state.marked_by) errors.push("marked_by must name the writer");
    if (typeof state.note !== "string" || !state.note) {
      errors.push("note must explain who writes the levels file and that the chart only reads it");
    }
    if (!Array.isArray(state.instruments)) {
      errors.push("instruments must be an array");
      return errors;
    }
    if (state.instrument_count !== state.instruments.length) {
      errors.push("instrument_count must equal the number of instrument entries");
    }

    const seenSymbols = new Set();
    state.instruments.forEach((instrument, index) => {
      const where = `instruments[${index}]`;
      if (!instrument || typeof instrument !== "object") {
        errors.push(`${where} must be an object`);
        return;
      }
      const symbol = typeof instrument.symbol === "string" ? instrument.symbol : "";
      if (!symbol) errors.push(`${where} requires a symbol`);
      if (seenSymbols.has(symbol)) errors.push(`Duplicate instrument entry: ${symbol}`);
      seenSymbols.add(symbol);
      if (typeof instrument.dashboard_asset !== "string" || !instrument.dashboard_asset) {
        errors.push(`Instrument ${symbol || where} requires dashboard_asset`);
      }
      if (!Array.isArray(instrument.levels)) {
        errors.push(`Instrument ${symbol || where} requires a levels array (empty when nothing is marked)`);
        return;
      }
      const seenPrices = new Set();
      instrument.levels.forEach((level, levelIndex) => {
        const at = `${symbol || where}.levels[${levelIndex}]`;
        if (!level || typeof level !== "object") {
          errors.push(`${at} must be an object`);
          return;
        }
        // Strictly a JSON number: the writers always write one, so a quoted price means a hand edit.
        const price = Number(level.price);
        if (!isFiniteNumber(level.price) || price <= 0) errors.push(`${at} requires a positive numeric price`);
        if (seenPrices.has(price)) errors.push(`${at} duplicates the price ${price} already marked for ${symbol}`);
        seenPrices.add(price);
        if (!ALLOWED_KINDS.includes(level.kind)) errors.push(`${at} kind must be one of ${ALLOWED_KINDS.join(", ")}`);
        if (!ALLOWED_DIRECTIONS.includes(level.direction)) {
          errors.push(`${at} direction must be one of ${ALLOWED_DIRECTIONS.join(", ")}`);
        }
        if (typeof level.timeframe !== "string" || !level.timeframe) errors.push(`${at} requires a timeframe`);
        if (typeof level.label !== "string" || !level.label) errors.push(`${at} requires a label`);
        if (!isTimestamp(level.marked_at_utc)) errors.push(`${at} requires a parseable marked_at_utc`);
        if (typeof level.marked_by !== "string" || !level.marked_by) errors.push(`${at} requires marked_by`);
        // `role` is optional so an older or hand-written file still validates; an unknown one is not.
        if (level.role !== undefined && !ALLOWED_ROLES.includes(level.role)) {
          errors.push(`${at} role must be one of ${ALLOWED_ROLES.join(", ")}`);
        }
        // A derived level is only meaningful with the measurement it came from, so the spacing and the
        // two anchors it was repeated between are required rather than decorative provenance.
        if (level.role === "derived") {
          if (!isFiniteNumber(level.spacing_price) || level.spacing_price <= 0) {
            errors.push(`${at} is derived and requires a positive spacing_price`);
          }
          if (!isFiniteNumber(level.anchor_high) || !isFiniteNumber(level.anchor_low) || level.anchor_high <= level.anchor_low) {
            errors.push(`${at} is derived and requires anchor_high above anchor_low`);
          }
          if (level.spacing_points !== null && level.spacing_points !== undefined
            && (!Number.isInteger(level.spacing_points) || level.spacing_points <= 0)) {
            errors.push(`${at} spacing_points must be a positive integer or null`);
          }
        }
      });
    });

    return errors;
  }

  // ---- The reader's own copy -------------------------------------------------------------------------
  // The published page has no server to write to, so a mark is kept in the reader's own browser first and
  // the commit to their own repository is what makes it durable and visible on the live page. The draft is
  // the safety net: a failed commit, a closed tab or a bad connection leaves the marks in place rather than
  // losing them, and they can be re-published or exported at any time. The repository is the durable copy.
  const DRAFT_KEY = "l2l-levels-draft-v1";
  const SETTINGS_KEY = "l2l-levels-publish-v1";
  const DEFAULT_REPO = "kevincreedycars-debug/trading-agent-dashboard";
  const DEFAULT_BRANCH = "main";

  function parseJsonObject(raw) {
    if (typeof raw !== "string" || !raw) return null;
    try {
      const parsed = JSON.parse(raw);
      return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : null;
    } catch (err) {
      return null;
    }
  }

  function storageGet(storage, key) {
    try {
      return storage && typeof storage.getItem === "function" ? storage.getItem(key) : null;
    } catch (err) {
      return null;
    }
  }

  function storageSet(storage, key, value) {
    try {
      if (storage && typeof storage.setItem === "function") {
        storage.setItem(key, value);
        return true;
      }
    } catch (err) {
      // A browser that refuses storage (private mode, a full quota) still works: the marks stay in the
      // page for this session and the Save a copy button is the way out.
    }
    return false;
  }

  function storageRemove(storage, key) {
    try {
      if (storage && typeof storage.removeItem === "function") storage.removeItem(key);
    } catch (err) {
      // Nothing to do: an unremovable key is not worth failing a marking session over.
    }
  }

  // A draft that no longer validates is ignored rather than loaded, so a half-written or hand-edited
  // browser entry cannot replace the published levels with something the chart would misread.
  function readDraft(persistent) {
    const raw = parseJsonObject(storageGet(persistent, DRAFT_KEY));
    if (!raw || !raw.state) return null;
    if (validateLevelsState(raw.state).length) return null;
    return {
      state: raw.state,
      saved_at_utc: typeof raw.saved_at_utc === "string" ? raw.saved_at_utc : null,
      base_sha: typeof raw.base_sha === "string" ? raw.base_sha : null
    };
  }

  function writeDraft(persistent, state, meta) {
    const payload = {
      saved_at_utc: meta?.saved_at_utc || new Date().toISOString(),
      base_sha: meta?.base_sha || null,
      state
    };
    return storageSet(persistent, DRAFT_KEY, JSON.stringify(payload));
  }

  function clearDraft(persistent) {
    storageRemove(persistent, DRAFT_KEY);
  }

  // Which of the two copies a page shows. Both can exist at once: the file committed to the repository,
  // which is what every reader sees and what makes a mark permanent, and a draft this reader made in their
  // own browser and has not published yet. A marked level is meant to stay until the person who marked it
  // moves it, so the committed file is the default and a draft is shown only when it is genuinely newer than
  // the file it would replace. A missing or unreadable stamp on either side falls back to the committed
  // file, because that copy is already durable and a draft that cannot prove it is newer must not hide it.
  function levelsStateStamp(value) {
    const parsed = Date.parse(typeof value === "string" ? value : "");
    return Number.isFinite(parsed) ? parsed : null;
  }

  function chooseLevelsView(published, draft) {
    const publishedState = published && typeof published === "object" && !Array.isArray(published) ? published : null;
    const draftState = draft && typeof draft === "object" && draft.state ? draft.state : null;
    const publishedAt = levelsStateStamp(publishedState?.generated_at_utc);
    // Only the draft's own saved-at stamp decides, and only when it can be read: a copy that cannot say when
    // it was made cannot claim to be newer than a committed file.
    const draftAt = levelsStateStamp(draft?.saved_at_utc);

    if (!draftState) {
      return {
        state: publishedState,
        source: publishedState ? "published" : "none",
        published_at_utc: publishedState?.generated_at_utc || null,
        draft_at_utc: null
      };
    }
    if (!publishedState) {
      return {
        state: draftState,
        source: "draft",
        published_at_utc: null,
        draft_at_utc: draft?.saved_at_utc || draftState.generated_at_utc || null
      };
    }
    const draftIsNewer = publishedAt !== null && draftAt !== null && draftAt > publishedAt;
    return draftIsNewer
      ? {
        state: draftState,
        source: "draft",
        published_at_utc: publishedState.generated_at_utc || null,
        draft_at_utc: draft?.saved_at_utc || null
      }
      : {
        state: publishedState,
        source: "published",
        published_at_utc: publishedState.generated_at_utc || null,
        draft_at_utc: draft?.saved_at_utc || null
      };
  }

  // The token is the reader's own GitHub token, entered by them in their own browser. It is never written
  // into the levels artifact, never sent anywhere but api.github.com, and kept only where the reader asked
  // for it to be kept: in this tab's session unless "remember on this device" is ticked, in which case it
  // goes to this browser's local storage. "Disconnect" removes it from both.
  function readSettings(persistent, session) {
    const device = parseJsonObject(storageGet(persistent, SETTINGS_KEY));
    const tab = parseJsonObject(storageGet(session, SETTINGS_KEY));
    const token = String(tab?.token || device?.token || "");
    return {
      repo: String(tab?.repo || device?.repo || DEFAULT_REPO),
      branch: String(tab?.branch || device?.branch || DEFAULT_BRANCH),
      remember: device?.remember === true,
      token,
      token_scope: tab?.token ? "session" : (device?.token ? "device" : "none")
    };
  }

  function writeSettings(persistent, session, settings) {
    const repo = String(settings?.repo || DEFAULT_REPO);
    const branch = String(settings?.branch || DEFAULT_BRANCH);
    const token = String(settings?.token || "");
    const remember = settings?.remember === true;
    storageRemove(persistent, SETTINGS_KEY);
    storageRemove(session, SETTINGS_KEY);
    const stored = storageSet(remember ? persistent : session, SETTINGS_KEY, JSON.stringify({
      repo,
      branch,
      remember,
      token
    }));
    return { stored, token_scope: !token ? "none" : (remember ? "device" : "session") };
  }

  function clearSettings(persistent, session) {
    storageRemove(persistent, SETTINGS_KEY);
    storageRemove(session, SETTINGS_KEY);
  }

  // ---- Publishing the file to the reader's own repository ---------------------------------------------
  // A commit through the GitHub contents API is what turns a mark made in a browser into the published
  // artifact, so this is the one outbound call the levels path makes. It reads one file and writes one
  // file, in the reader's own account, with the reader's own token: no service of ours, no key of ours, and
  // nothing about the trading account. The token is only ever used as a request header.
  const API_ROOT = "https://api.github.com";
  const API_VERSION = "2022-11-28";

  function parseRepo(value) {
    const raw = String(value || "").trim();
    if (!raw) return null;
    const cleaned = raw
      .replace(/^https?:\/\/github\.com\//i, "")
      .replace(/\.git$/i, "")
      .replace(/\/+$/, "");
    const parts = cleaned.split("/").filter(Boolean);
    if (parts.length !== 2) return null;
    if (!/^[A-Za-z0-9._-]+$/.test(parts[0]) || !/^[A-Za-z0-9._-]+$/.test(parts[1])) return null;
    return { owner: parts[0], repo: parts[1] };
  }

  // A path keeps its slashes and encodes everything else, so `data/l2l-levels.json` stays a path.
  function encodeContentPath(path) {
    return String(path).split("/").map(segment => encodeURIComponent(segment)).join("/");
  }

  function toBase64(text) {
    const value = String(text);
    if (typeof Buffer === "function" && typeof Buffer.from === "function") {
      return Buffer.from(value, "utf8").toString("base64");
    }
    const bytes = new TextEncoder().encode(value);
    let binary = "";
    bytes.forEach(byte => { binary += String.fromCharCode(byte); });
    return btoa(binary);
  }

  function fromBase64(encoded) {
    const value = String(encoded).replace(/\s+/g, "");
    if (typeof Buffer === "function" && typeof Buffer.from === "function") {
      return Buffer.from(value, "base64").toString("utf8");
    }
    const binary = atob(value);
    const bytes = Uint8Array.from(binary, character => character.charCodeAt(0));
    return new TextDecoder().decode(bytes);
  }

  function contentsUrl(owner, repo, path) {
    return `${API_ROOT}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${encodeContentPath(path)}`;
  }

  function githubHeaders(token) {
    return {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": API_VERSION
    };
  }

  // Both halves of the exchange, in the shape fetch() takes them, so a test can assert the request without
  // a network: the read carries no body, the write carries the file and, when the file exists, its sha.
  function buildReadRequest({ owner, repo, branch, token, path }) {
    const url = `${contentsUrl(owner, repo, path)}?ref=${encodeURIComponent(branch)}`;
    return { url, init: { method: "GET", headers: githubHeaders(token) } };
  }

  function buildCommitRequest({ owner, repo, branch, token, path, content, sha, message }) {
    const body = { message, content: toBase64(content), branch };
    if (sha) body.sha = sha;
    return {
      url: contentsUrl(owner, repo, path),
      init: { method: "PUT", headers: githubHeaders(token), body: JSON.stringify(body) }
    };
  }

  // Every failure says what to do about it and never repeats what was sent, so a token cannot be printed by
  // accident into a status line, a console log or a screenshot.
  function describeStatus(status) {
    if (status === 401) {
      return "GitHub refused the token (401). Check it is valid, not expired, and allowed Contents: read and write on this repository.";
    }
    if (status === 403) {
      return "GitHub refused the request (403). The token may lack Contents: read and write on this repository, or the API rate limit was reached.";
    }
    if (status === 404) {
      return "GitHub answered 404. Check the repository name, and that the token is allowed to write Contents there.";
    }
    if (status === 409 || status === 422) {
      return "GitHub rejected the write because the file changed since this page read it (409/422). Reload the page and publish again.";
    }
    if (status >= 500) {
      return `GitHub answered ${status}, so the commit did not happen. The marks are still saved on this device.`;
    }
    return `GitHub answered ${status}, so the commit did not happen.`;
  }

  async function readRemoteLevels({ fetchImpl, owner, repo, branch, token, path }) {
    const send = fetchImpl || (typeof fetch === "function" ? fetch : null);
    if (!send) return { ok: false, status: 0, error: "This browser cannot reach GitHub for a commit." };
    let response;
    try {
      const request = buildReadRequest({ owner, repo, branch, token, path });
      response = await send(request.url, { ...request.init, cache: "no-store" });
    } catch (error) {
      return { ok: false, status: 0, error: `Could not reach GitHub: ${error.message}` };
    }
    if (response.status === 404) {
      // Not an error: the file may simply not be in the repository yet, and the first publish creates it.
      return { ok: true, status: 404, sha: null, state: null, missing: true };
    }
    if (!response.ok) {
      return { ok: false, status: response.status, error: describeStatus(response.status) };
    }
    let payload;
    try {
      payload = await response.json();
    } catch (error) {
      return { ok: false, status: response.status, error: "GitHub's answer could not be read as JSON." };
    }
    let state = null;
    if (typeof payload?.content === "string" && payload.content) {
      try {
        state = JSON.parse(fromBase64(payload.content));
      } catch (error) {
        state = null;
      }
    }
    return {
      ok: true,
      status: response.status,
      sha: typeof payload?.sha === "string" ? payload.sha : null,
      state,
      missing: false
    };
  }

  // The commit refuses to write a file the checker would reject, and refuses to overwrite a published file
  // that moved since the page read it unless the reader says to. Both refusals leave the browser draft
  // untouched, which is what makes the order of the two stores safe: GitHub decides what is published, the
  // browser holds what has not been published yet.
  async function commitLevels({ fetchImpl, owner, repo, branch, token, path, state, message, expectedSha, force }) {
    const problems = validateLevelsState(state);
    if (problems.length) {
      return { ok: false, status: 0, error: `Refusing to publish a levels file that would not validate: ${problems.join("; ")}` };
    }
    if (!token) {
      return { ok: false, status: 0, error: "A GitHub token is needed to publish. Paste one and try again." };
    }
    const remote = await readRemoteLevels({ fetchImpl, owner, repo, branch, token, path });
    if (!remote.ok) return remote;
    if (expectedSha && remote.sha && remote.sha !== expectedSha && force !== true) {
      return {
        ok: false,
        status: 409,
        conflict: true,
        sha: remote.sha,
        error: "The published file changed on GitHub since this page read it, so publishing would replace a newer version. Reload the page, or publish anyway to overwrite it."
      };
    }

    const send = fetchImpl || (typeof fetch === "function" ? fetch : null);
    let response;
    try {
      const request = buildCommitRequest({
        owner,
        repo,
        branch,
        token,
        path,
        content: serialiseState(state),
        sha: remote.sha,
        message
      });
      response = await send(request.url, request.init);
    } catch (error) {
      return { ok: false, status: 0, error: `Could not reach GitHub: ${error.message}` };
    }
    if (!response.ok) {
      return { ok: false, status: response.status, error: describeStatus(response.status) };
    }
    let payload = null;
    try {
      payload = await response.json();
    } catch (error) {
      payload = null;
    }
    return {
      ok: true,
      status: response.status,
      sha: typeof payload?.content?.sha === "string" ? payload.content.sha : null,
      commit_sha: typeof payload?.commit?.sha === "string" ? payload.commit.sha : null,
      commit_url: typeof payload?.commit?.html_url === "string" ? payload.commit.html_url : ""
    };
  }

  // What the page fills in and what the request needs, in one place: a repository the reader typed, the
  // branch it publishes from, and the one path in it this capability may touch.
  function normalisePublishTarget({ repo, branch, path } = {}) {
    const parsed = parseRepo(repo);
    if (!parsed) {
      return { ok: false, error: "The repository must be written as owner/repo, for example kevincreedycars-debug/trading-agent-dashboard." };
    }
    return {
      ok: true,
      owner: parsed.owner,
      repo: parsed.repo,
      branch: String(branch || DEFAULT_BRANCH),
      path: String(path || DEFAULT_STATE_PATH)
    };
  }

  return {
    SCHEMA_VERSION,
    DEFAULT_STATE_PATH,
    DEFAULT_PORT,
    ALLOWED_KINDS,
    ALLOWED_DIRECTIONS,
    ALLOWED_ROLES,
    ALLOWED_ACTIONS,
    DERIVED_MARKED_BY,
    DEFAULT_DUPLICATE_STEPS,
    MAX_DUPLICATE_STEPS,
    DEFAULT_TIMEFRAME,
    KNOWN_INSTRUMENTS,
    PRICE_TOLERANCE,
    LEVEL_MARKED_BY,
    MARKED_BY,
    NOTE,
    isFiniteNumber,
    isTimestamp,
    roundPrice,
    createEmptyState,
    stateInstrumentMap,
    normaliseStepCount,
    normaliseEdit,
    buildLadder,
    applyLevelEdit,
    serialiseState,
    validateLevelsState,
    DRAFT_KEY,
    SETTINGS_KEY,
    DEFAULT_REPO,
    DEFAULT_BRANCH,
    parseJsonObject,
    storageGet,
    storageSet,
    storageRemove,
    readDraft,
    writeDraft,
    clearDraft,
    levelsStateStamp,
    chooseLevelsView,
    readSettings,
    writeSettings,
    clearSettings,
    API_ROOT,
    API_VERSION,
    parseRepo,
    encodeContentPath,
    toBase64,
    fromBase64,
    contentsUrl,
    githubHeaders,
    buildReadRequest,
    buildCommitRequest,
    describeStatus,
    readRemoteLevels,
    commitLevels,
    normalisePublishTarget
  };
});
